version: '3'
services:
  api:
    build: ./API/
    network_mode: host
    depends_on:
      - db
  db:
    build: ./data_storage/
    network_mode: host

  gathering_data:
    build: ./Gathering_DATA/
    network_mode: host
    depends_on:
      - db

  display:
    build: ./Display/
    network_mode: host
    depends_on:
      - api
